// Code generated by "stringer -type=Message"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WM_KEYDOWN-256]
	_ = x[WM_KEYUP-257]
	_ = x[WM_SYSKEYDOWN-260]
	_ = x[WM_SYSKEYUP-261]
}

const (
	_Message_name_0 = "WM_KEYDOWNWM_KEYUP"
	_Message_name_1 = "WM_SYSKEYDOWNWM_SYSKEYUP"
)

var (
	_Message_index_0 = [...]uint8{0, 10, 18}
	_Message_index_1 = [...]uint8{0, 13, 24}
)

func (i Message) String() string {
	switch {
	case 256 <= i && i <= 257:
		i -= 256
		return _Message_name_0[_Message_index_0[i]:_Message_index_0[i+1]]
	case 260 <= i && i <= 261:
		i -= 260
		return _Message_name_1[_Message_index_1[i]:_Message_index_1[i+1]]
	default:
		return "Message(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
