// Code generated by "stringer -type=VKCode"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VK_LBUTTON-1]
	_ = x[VK_RBUTTON-2]
	_ = x[VK_CANCEL-3]
	_ = x[VK_MBUTTON-4]
	_ = x[VK_XBUTTON1-5]
	_ = x[VK_XBUTTON2-6]
	_ = x[VK_BACK-8]
	_ = x[VK_TAB-9]
	_ = x[VK_CLEAR-12]
	_ = x[VK_RETURN-13]
	_ = x[VK_SHIFT-16]
	_ = x[VK_CONTROL-17]
	_ = x[VK_MENU-18]
	_ = x[VK_PAUSE-19]
	_ = x[VK_CAPITAL-20]
	_ = x[VK_KANA-21]
	_ = x[VK_HANGUEL-21]
	_ = x[VK_HANGUL-21]
	_ = x[VK_IME_ON-22]
	_ = x[VK_JUNJA-23]
	_ = x[VK_FINAL-24]
	_ = x[VK_HANJA-25]
	_ = x[VK_KANJI-25]
	_ = x[VK_IME_OFF-26]
	_ = x[VK_ESCAPE-27]
	_ = x[VK_CONVERT-28]
	_ = x[VK_NONCONVERT-29]
	_ = x[VK_ACCEPT-30]
	_ = x[VK_MODECHANGE-31]
	_ = x[VK_SPACE-32]
	_ = x[VK_PRIOR-33]
	_ = x[VK_NEXT-34]
	_ = x[VK_END-35]
	_ = x[VK_HOME-36]
	_ = x[VK_LEFT-37]
	_ = x[VK_UP-38]
	_ = x[VK_RIGHT-39]
	_ = x[VK_DOWN-40]
	_ = x[VK_SELECT-41]
	_ = x[VK_PRINT-42]
	_ = x[VK_EXECUTE-43]
	_ = x[VK_SNAPSHOT-44]
	_ = x[VK_INSERT-45]
	_ = x[VK_DELETE-46]
	_ = x[VK_HELP-47]
	_ = x[VK_0-48]
	_ = x[VK_1-49]
	_ = x[VK_2-50]
	_ = x[VK_3-51]
	_ = x[VK_4-52]
	_ = x[VK_5-53]
	_ = x[VK_6-54]
	_ = x[VK_7-55]
	_ = x[VK_8-56]
	_ = x[VK_9-57]
	_ = x[VK_A-65]
	_ = x[VK_B-66]
	_ = x[VK_C-67]
	_ = x[VK_D-68]
	_ = x[VK_E-69]
	_ = x[VK_F-70]
	_ = x[VK_G-71]
	_ = x[VK_H-72]
	_ = x[VK_I-73]
	_ = x[VK_J-74]
	_ = x[VK_K-75]
	_ = x[VK_L-76]
	_ = x[VK_M-77]
	_ = x[VK_N-78]
	_ = x[VK_O-79]
	_ = x[VK_P-80]
	_ = x[VK_Q-81]
	_ = x[VK_R-82]
	_ = x[VK_S-83]
	_ = x[VK_T-84]
	_ = x[VK_U-85]
	_ = x[VK_V-86]
	_ = x[VK_W-87]
	_ = x[VK_X-88]
	_ = x[VK_Y-89]
	_ = x[VK_Z-90]
	_ = x[VK_LWIN-91]
	_ = x[VK_RWIN-92]
	_ = x[VK_APPS-93]
	_ = x[VK_SLEEP-95]
	_ = x[VK_NUMPAD0-96]
	_ = x[VK_NUMPAD1-97]
	_ = x[VK_NUMPAD2-98]
	_ = x[VK_NUMPAD3-99]
	_ = x[VK_NUMPAD4-100]
	_ = x[VK_NUMPAD5-101]
	_ = x[VK_NUMPAD6-102]
	_ = x[VK_NUMPAD7-103]
	_ = x[VK_NUMPAD8-104]
	_ = x[VK_NUMPAD9-105]
	_ = x[VK_MULTIPLY-106]
	_ = x[VK_ADD-107]
	_ = x[VK_SEPARATOR-108]
	_ = x[VK_SUBTRACT-109]
	_ = x[VK_DECIMAL-110]
	_ = x[VK_DIVIDE-111]
	_ = x[VK_F1-112]
	_ = x[VK_F2-113]
	_ = x[VK_F3-114]
	_ = x[VK_F4-115]
	_ = x[VK_F5-116]
	_ = x[VK_F6-117]
	_ = x[VK_F7-118]
	_ = x[VK_F8-119]
	_ = x[VK_F9-120]
	_ = x[VK_F10-121]
	_ = x[VK_F11-122]
	_ = x[VK_F12-123]
	_ = x[VK_F13-124]
	_ = x[VK_F14-125]
	_ = x[VK_F15-126]
	_ = x[VK_F16-127]
	_ = x[VK_F17-128]
	_ = x[VK_F18-129]
	_ = x[VK_F19-130]
	_ = x[VK_F20-131]
	_ = x[VK_F21-132]
	_ = x[VK_F22-133]
	_ = x[VK_F23-134]
	_ = x[VK_F24-135]
	_ = x[VK_NUMLOCK-144]
	_ = x[VK_SCROLL-145]
	_ = x[VK_LSHIFT-160]
	_ = x[VK_RSHIFT-161]
	_ = x[VK_LCONTROL-162]
	_ = x[VK_RCONTROL-163]
	_ = x[VK_LMENU-164]
	_ = x[VK_RMENU-165]
	_ = x[VK_BROWSER_BACK-166]
	_ = x[VK_BROWSER_FORWARD-167]
	_ = x[VK_BROWSER_REFRESH-168]
	_ = x[VK_BROWSER_STOP-169]
	_ = x[VK_BROWSER_SEARCH-170]
	_ = x[VK_BROWSER_FAVORITES-171]
	_ = x[VK_BROWSER_HOME-172]
	_ = x[VK_VOLUME_MUTE-173]
	_ = x[VK_VOLUME_DOWN-174]
	_ = x[VK_VOLUME_UP-175]
	_ = x[VK_MEDIA_NEXT_TRACK-176]
	_ = x[VK_MEDIA_PREV_TRACK-177]
	_ = x[VK_MEDIA_STOP-178]
	_ = x[VK_MEDIA_PLAY_PAUSE-179]
	_ = x[VK_LAUNCH_MAIL-180]
	_ = x[VK_LAUNCH_MEDIA_SELECT-181]
	_ = x[VK_LAUNCH_APP1-182]
	_ = x[VK_LAUNCH_APP2-183]
	_ = x[VK_OEM_1-186]
	_ = x[VK_OEM_PLUS-187]
	_ = x[VK_OEM_COMMA-188]
	_ = x[VK_OEM_MINUS-189]
	_ = x[VK_OEM_PERIOD-190]
	_ = x[VK_OEM_2-191]
	_ = x[VK_OEM_3-192]
	_ = x[VK_OEM_4-219]
	_ = x[VK_OEM_5-220]
	_ = x[VK_OEM_6-221]
	_ = x[VK_OEM_7-222]
	_ = x[VK_OEM_8-223]
	_ = x[VK_OEM_102-226]
	_ = x[VK_PROCESSKEY-229]
	_ = x[VK_PACKET-231]
	_ = x[VK_ATTN-246]
	_ = x[VK_CRSEL-247]
	_ = x[VK_EXSEL-248]
	_ = x[VK_EREOF-249]
	_ = x[VK_PLAY-250]
	_ = x[VK_ZOOM-251]
	_ = x[VK_NONAME-252]
	_ = x[VK_PA1-253]
	_ = x[VK_OEM_CLEAR-254]
}

const _VKCode_name = "VK_LBUTTONVK_RBUTTONVK_CANCELVK_MBUTTONVK_XBUTTON1VK_XBUTTON2VK_BACKVK_TABVK_CLEARVK_RETURNVK_SHIFTVK_CONTROLVK_MENUVK_PAUSEVK_CAPITALVK_KANAVK_IME_ONVK_JUNJAVK_FINALVK_HANJAVK_IME_OFFVK_ESCAPEVK_CONVERTVK_NONCONVERTVK_ACCEPTVK_MODECHANGEVK_SPACEVK_PRIORVK_NEXTVK_ENDVK_HOMEVK_LEFTVK_UPVK_RIGHTVK_DOWNVK_SELECTVK_PRINTVK_EXECUTEVK_SNAPSHOTVK_INSERTVK_DELETEVK_HELPVK_0VK_1VK_2VK_3VK_4VK_5VK_6VK_7VK_8VK_9VK_AVK_BVK_CVK_DVK_EVK_FVK_GVK_HVK_IVK_JVK_KVK_LVK_MVK_NVK_OVK_PVK_QVK_RVK_SVK_TVK_UVK_VVK_WVK_XVK_YVK_ZVK_LWINVK_RWINVK_APPSVK_SLEEPVK_NUMPAD0VK_NUMPAD1VK_NUMPAD2VK_NUMPAD3VK_NUMPAD4VK_NUMPAD5VK_NUMPAD6VK_NUMPAD7VK_NUMPAD8VK_NUMPAD9VK_MULTIPLYVK_ADDVK_SEPARATORVK_SUBTRACTVK_DECIMALVK_DIVIDEVK_F1VK_F2VK_F3VK_F4VK_F5VK_F6VK_F7VK_F8VK_F9VK_F10VK_F11VK_F12VK_F13VK_F14VK_F15VK_F16VK_F17VK_F18VK_F19VK_F20VK_F21VK_F22VK_F23VK_F24VK_NUMLOCKVK_SCROLLVK_LSHIFTVK_RSHIFTVK_LCONTROLVK_RCONTROLVK_LMENUVK_RMENUVK_BROWSER_BACKVK_BROWSER_FORWARDVK_BROWSER_REFRESHVK_BROWSER_STOPVK_BROWSER_SEARCHVK_BROWSER_FAVORITESVK_BROWSER_HOMEVK_VOLUME_MUTEVK_VOLUME_DOWNVK_VOLUME_UPVK_MEDIA_NEXT_TRACKVK_MEDIA_PREV_TRACKVK_MEDIA_STOPVK_MEDIA_PLAY_PAUSEVK_LAUNCH_MAILVK_LAUNCH_MEDIA_SELECTVK_LAUNCH_APP1VK_LAUNCH_APP2VK_OEM_1VK_OEM_PLUSVK_OEM_COMMAVK_OEM_MINUSVK_OEM_PERIODVK_OEM_2VK_OEM_3VK_OEM_4VK_OEM_5VK_OEM_6VK_OEM_7VK_OEM_8VK_OEM_102VK_PROCESSKEYVK_PACKETVK_ATTNVK_CRSELVK_EXSELVK_EREOFVK_PLAYVK_ZOOMVK_NONAMEVK_PA1VK_OEM_CLEAR"

var _VKCode_map = map[VKCode]string{
	1:   _VKCode_name[0:10],
	2:   _VKCode_name[10:20],
	3:   _VKCode_name[20:29],
	4:   _VKCode_name[29:39],
	5:   _VKCode_name[39:50],
	6:   _VKCode_name[50:61],
	8:   _VKCode_name[61:68],
	9:   _VKCode_name[68:74],
	12:  _VKCode_name[74:82],
	13:  _VKCode_name[82:91],
	16:  _VKCode_name[91:99],
	17:  _VKCode_name[99:109],
	18:  _VKCode_name[109:116],
	19:  _VKCode_name[116:124],
	20:  _VKCode_name[124:134],
	21:  _VKCode_name[134:141],
	22:  _VKCode_name[141:150],
	23:  _VKCode_name[150:158],
	24:  _VKCode_name[158:166],
	25:  _VKCode_name[166:174],
	26:  _VKCode_name[174:184],
	27:  _VKCode_name[184:193],
	28:  _VKCode_name[193:203],
	29:  _VKCode_name[203:216],
	30:  _VKCode_name[216:225],
	31:  _VKCode_name[225:238],
	32:  _VKCode_name[238:246],
	33:  _VKCode_name[246:254],
	34:  _VKCode_name[254:261],
	35:  _VKCode_name[261:267],
	36:  _VKCode_name[267:274],
	37:  _VKCode_name[274:281],
	38:  _VKCode_name[281:286],
	39:  _VKCode_name[286:294],
	40:  _VKCode_name[294:301],
	41:  _VKCode_name[301:310],
	42:  _VKCode_name[310:318],
	43:  _VKCode_name[318:328],
	44:  _VKCode_name[328:339],
	45:  _VKCode_name[339:348],
	46:  _VKCode_name[348:357],
	47:  _VKCode_name[357:364],
	48:  _VKCode_name[364:368],
	49:  _VKCode_name[368:372],
	50:  _VKCode_name[372:376],
	51:  _VKCode_name[376:380],
	52:  _VKCode_name[380:384],
	53:  _VKCode_name[384:388],
	54:  _VKCode_name[388:392],
	55:  _VKCode_name[392:396],
	56:  _VKCode_name[396:400],
	57:  _VKCode_name[400:404],
	65:  _VKCode_name[404:408],
	66:  _VKCode_name[408:412],
	67:  _VKCode_name[412:416],
	68:  _VKCode_name[416:420],
	69:  _VKCode_name[420:424],
	70:  _VKCode_name[424:428],
	71:  _VKCode_name[428:432],
	72:  _VKCode_name[432:436],
	73:  _VKCode_name[436:440],
	74:  _VKCode_name[440:444],
	75:  _VKCode_name[444:448],
	76:  _VKCode_name[448:452],
	77:  _VKCode_name[452:456],
	78:  _VKCode_name[456:460],
	79:  _VKCode_name[460:464],
	80:  _VKCode_name[464:468],
	81:  _VKCode_name[468:472],
	82:  _VKCode_name[472:476],
	83:  _VKCode_name[476:480],
	84:  _VKCode_name[480:484],
	85:  _VKCode_name[484:488],
	86:  _VKCode_name[488:492],
	87:  _VKCode_name[492:496],
	88:  _VKCode_name[496:500],
	89:  _VKCode_name[500:504],
	90:  _VKCode_name[504:508],
	91:  _VKCode_name[508:515],
	92:  _VKCode_name[515:522],
	93:  _VKCode_name[522:529],
	95:  _VKCode_name[529:537],
	96:  _VKCode_name[537:547],
	97:  _VKCode_name[547:557],
	98:  _VKCode_name[557:567],
	99:  _VKCode_name[567:577],
	100: _VKCode_name[577:587],
	101: _VKCode_name[587:597],
	102: _VKCode_name[597:607],
	103: _VKCode_name[607:617],
	104: _VKCode_name[617:627],
	105: _VKCode_name[627:637],
	106: _VKCode_name[637:648],
	107: _VKCode_name[648:654],
	108: _VKCode_name[654:666],
	109: _VKCode_name[666:677],
	110: _VKCode_name[677:687],
	111: _VKCode_name[687:696],
	112: _VKCode_name[696:701],
	113: _VKCode_name[701:706],
	114: _VKCode_name[706:711],
	115: _VKCode_name[711:716],
	116: _VKCode_name[716:721],
	117: _VKCode_name[721:726],
	118: _VKCode_name[726:731],
	119: _VKCode_name[731:736],
	120: _VKCode_name[736:741],
	121: _VKCode_name[741:747],
	122: _VKCode_name[747:753],
	123: _VKCode_name[753:759],
	124: _VKCode_name[759:765],
	125: _VKCode_name[765:771],
	126: _VKCode_name[771:777],
	127: _VKCode_name[777:783],
	128: _VKCode_name[783:789],
	129: _VKCode_name[789:795],
	130: _VKCode_name[795:801],
	131: _VKCode_name[801:807],
	132: _VKCode_name[807:813],
	133: _VKCode_name[813:819],
	134: _VKCode_name[819:825],
	135: _VKCode_name[825:831],
	144: _VKCode_name[831:841],
	145: _VKCode_name[841:850],
	160: _VKCode_name[850:859],
	161: _VKCode_name[859:868],
	162: _VKCode_name[868:879],
	163: _VKCode_name[879:890],
	164: _VKCode_name[890:898],
	165: _VKCode_name[898:906],
	166: _VKCode_name[906:921],
	167: _VKCode_name[921:939],
	168: _VKCode_name[939:957],
	169: _VKCode_name[957:972],
	170: _VKCode_name[972:989],
	171: _VKCode_name[989:1009],
	172: _VKCode_name[1009:1024],
	173: _VKCode_name[1024:1038],
	174: _VKCode_name[1038:1052],
	175: _VKCode_name[1052:1064],
	176: _VKCode_name[1064:1083],
	177: _VKCode_name[1083:1102],
	178: _VKCode_name[1102:1115],
	179: _VKCode_name[1115:1134],
	180: _VKCode_name[1134:1148],
	181: _VKCode_name[1148:1170],
	182: _VKCode_name[1170:1184],
	183: _VKCode_name[1184:1198],
	186: _VKCode_name[1198:1206],
	187: _VKCode_name[1206:1217],
	188: _VKCode_name[1217:1229],
	189: _VKCode_name[1229:1241],
	190: _VKCode_name[1241:1254],
	191: _VKCode_name[1254:1262],
	192: _VKCode_name[1262:1270],
	219: _VKCode_name[1270:1278],
	220: _VKCode_name[1278:1286],
	221: _VKCode_name[1286:1294],
	222: _VKCode_name[1294:1302],
	223: _VKCode_name[1302:1310],
	226: _VKCode_name[1310:1320],
	229: _VKCode_name[1320:1333],
	231: _VKCode_name[1333:1342],
	246: _VKCode_name[1342:1349],
	247: _VKCode_name[1349:1357],
	248: _VKCode_name[1357:1365],
	249: _VKCode_name[1365:1373],
	250: _VKCode_name[1373:1380],
	251: _VKCode_name[1380:1387],
	252: _VKCode_name[1387:1396],
	253: _VKCode_name[1396:1402],
	254: _VKCode_name[1402:1414],
}

func (i VKCode) String() string {
	if str, ok := _VKCode_map[i]; ok {
		return str
	}
	return "VKCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
